import {it,expect,vi} from 'vitest';
import {render,screen,fireEvent} from '@testing-library/react';
import {rankCatalogItems,matchesCatalogItemSearch} from '@/services/materials/material-search';
import {MaterialSearchSelect} from '@/features/materials/components/MaterialSearchSelect';
const material=(name:string,sku:string,aliases:string[]=[])=>({id:sku,name,sku,aliases,unit:'each',category:'Electrical',notes:null} as any);
const box=material('Steel device box','BOX-100',['switch box']);
const breaker=material('Single pole breaker 20 amp','BR-20');
const wire12=material('NMD90 copper wire 12/2','WIRE12');
const wire14=material('NMD90 copper wire 14/2','WIRE14');
it('requires all words instead of allowing one unrelated match',()=>{expect(matchesCatalogItemSearch(box,'steel breaker')).toBe(false);expect(matchesCatalogItemSearch(breaker,'steel breaker')).toBe(false);});
it('ranks exact supplier codes before name mentions and tolerates separators',()=>{expect(rankCatalogItems([material('Replacement for BOX-100','other'),box],'box100')[0]).toBe(box);});
it('supports nicknames and reordered words',()=>{expect(rankCatalogItems([breaker,box],'box switch')).toEqual([box]);});
it('tolerates one spelling error and swapped letters',()=>{expect(matchesCatalogItemSearch(breaker,'breakr')).toBe(true);expect(matchesCatalogItemSearch(breaker,'braeker')).toBe(true);});
it('keeps numeric specifications exact',()=>{expect(rankCatalogItems([wire14,wire12],'wire 12/2')).toEqual([wire12]);expect(matchesCatalogItemSearch(material('120 volt device','V120'),'12')).toBe(false);});
it('does not mistake fractions for an unrelated all-numeric code',()=>{expect(matchesCatalogItemSearch(material('Unrelated item','122'),'12/2')).toBe(false);});
it('keeps trade-name normalization',()=>{expect(matchesCatalogItemSearch(material('Recessed light','LIGHT'),'pot light')).toBe(true);expect(matchesCatalogItemSearch(wire12,'romex 12/2')).toBe(true);});
it('puts an exact material name above incidental notes',()=>{const extra={...breaker,notes:'steel device box'};expect(rankCatalogItems([extra,box],'Steel device box')[0]).toBe(box);});
it('supports keyboard selection without submitting the surrounding form',()=>{const select=vi.fn(),submit=vi.fn();render(<form onSubmit={submit}><MaterialSearchSelect catalogItems={[breaker,box]} selectedMaterialId="" isPending={false} onSelect={select}/></form>);const input=screen.getByRole('combobox');fireEvent.focus(input);fireEvent.change(input,{target:{value:'switch box'}});fireEvent.keyDown(input,{key:'ArrowDown'});fireEvent.keyDown(input,{key:'Enter'});expect(select).toHaveBeenCalledWith('BOX-100');expect(submit).not.toHaveBeenCalled();expect(screen.queryByRole('listbox')).toBeNull();});
it('Escape closes the matches without choosing a material',()=>{const select=vi.fn();render(<MaterialSearchSelect catalogItems={[box]} selectedMaterialId="" isPending={false} onSelect={select}/>);const input=screen.getByRole('combobox');fireEvent.focus(input);fireEvent.keyDown(input,{key:'Escape'});expect(select).not.toHaveBeenCalled();expect(screen.queryByRole('listbox')).toBeNull();});
it('handles older items without alias metadata',()=>{expect(matchesCatalogItemSearch({...box,aliases:undefined},'steel')).toBe(true);});
