import { describe,it,expect,vi } from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {FieldMaterialsUsedPanel} from '@/features/field/components/FieldMaterialsUsedPanel';
import {JobTaskBoard} from '@/features/jobs/components/JobTaskBoard';
import {parseMaterialQuantity,readTaskContext,writeTaskContext,jobTasks,collectJobParts} from '@/services/jobs/job-organization';
import {JobMaterialsRepositoryImpl} from '@/data/repositories/job-materials.repository.impl';
const item:any={id:'material',name:'Copper wire',sku:'WIRE',unit:'m',costPrice:2,unitPrice:3,aliases:['wire'],isActive:true};
function panel(overrides:any={}) { const props={jobId:'job',draftScope:'org:user',parts:['General','Service','Shop'],catalogItems:[item],assemblies:[],usedMaterials:[],plannedMaterialIds:['material'],onCreateUsedMaterial:vi.fn().mockResolvedValue({}),onUpdateUsedMaterial:vi.fn().mockResolvedValue({}),onDeleteUsedMaterial:vi.fn().mockResolvedValue({}),...overrides};return {props,...render(<FieldMaterialsUsedPanel {...props}/>)}; }
describe('material quantities and job context',()=>{
 it('rejects ambiguous or invalid quantities without rounding away detail',()=>{for(const value of ['','0','-2','1.234','1,5','abc','1e3','Infinity'])expect(parseMaterialQuantity(value)).toBeNull();expect(parseMaterialQuantity('12.25')).toBe(12.25);});
 it('preserves legacy notes and round trips parts',()=>{expect(readTaskContext('Check panel')).toEqual({part:'General',detail:'Check panel'});expect(readTaskContext(writeTaskContext('Service','East wall'))).toEqual({part:'Service',detail:'East wall'});expect(collectJobParts([{sectionName:'General'},{sectionName:'Service'}],[{sectionName:'Service'}])).toEqual(['General','Service']);});
 it('does not include another job or time-entry followup',()=>{expect(jobTasks([{id:'a',entityType:'jobs',entityId:'job',status:'open'},{id:'b',entityType:'time_entries',entityId:'job',status:'open'}] as any,'job').map(x=>x.id)).toEqual(['a']);});
});
describe('field material entry',()=>{
 it('saves exact quantity to selected part and does not merge same SKU from another part',async()=>{const {props}=panel({usedMaterials:[{...item,id:'old',catalogItemId:'material',quantity:10,sectionName:'Shop',createdAt:'2026-01-01'}]});fireEvent.click(screen.getByRole('button',{name:'Choose Copper wire'}));fireEvent.change(screen.getByLabelText('Quantity used (m)'),{target:{value:'12.25'}});fireEvent.change(screen.getByLabelText('Job part',{selector:'select'}),{target:{value:'Service'}});fireEvent.click(screen.getByRole('button',{name:'Add 12.25 m used'}));await waitFor(()=>expect(props.onCreateUsedMaterial).toHaveBeenCalledTimes(1));expect(props.onCreateUsedMaterial.mock.calls[0][0]).toMatchObject({quantity:12.25,sectionName:'Service',catalogItemId:'material'});expect(props.onUpdateUsedMaterial).not.toHaveBeenCalled();await screen.findByRole('status');});
 it('retains failed draft across remount and retries with the same request ID',async()=>{const save=vi.fn().mockRejectedValue(new Error('Connection lost'));const view=panel({onCreateUsedMaterial:save});fireEvent.click(screen.getByRole('button',{name:'Choose Copper wire'}));fireEvent.click(screen.getByRole('button',{name:'Add 1 m used'}));await screen.findByRole('alert');const requestId=save.mock.calls[0][0].requestId;view.unmount();panel({onCreateUsedMaterial:save});expect((screen.getByLabelText('Quantity used (m)') as HTMLInputElement).value).toBe('1');fireEvent.click(screen.getByRole('button',{name:'Add 1 m used'}));await waitFor(()=>expect(save).toHaveBeenCalledTimes(2));expect(save.mock.calls[1][0].requestId).toBe(requestId);});
 it('blocks repeated taps during save',async()=>{let finish:any;const save=vi.fn(()=>new Promise(resolve=>finish=resolve));panel({onCreateUsedMaterial:save});fireEvent.click(screen.getByRole('button',{name:'Choose Copper wire'}));fireEvent.click(screen.getByRole('button',{name:'Add 1 m used'}));fireEvent.click(screen.getByRole('button',{name:'Saving…'}));expect(save).toHaveBeenCalledTimes(1);finish({});await screen.findByRole('status');});
 it('requires confirmation before removing a saved entry',async()=>{const {props}=panel({usedMaterials:[{...item,id:'old',catalogItemId:'material',quantity:10,sectionName:'Shop',createdAt:'2026-01-01'}]});fireEvent.click(screen.getByRole('button',{name:'Remove',exact:true}));expect(props.onDeleteUsedMaterial).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Keep entry'}));expect(props.onDeleteUsedMaterial).not.toHaveBeenCalled();});
});
describe('job tasks',()=>{
 const task:any={id:'t',entityType:'jobs',entityId:'job',title:'Label panel',description:writeTaskContext('Service','Use circuit schedule'),assignedTo:'worker',status:'open',createdAt:'2026-01-01'};
 it('allows assigned field worker to complete but does not offer office-only create',async()=>{const complete=vi.fn().mockResolvedValue({});render(<JobTaskBoard jobId="job" items={[task]} parts={['General','Service']} currentUser={{id:'worker',fullName:'Worker',role:'field'} as any} crew={[]} canCreate={false} onCreate={vi.fn()} onComplete={complete}/>);expect(screen.queryByRole('button',{name:'+ Add task'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Mark Label panel done'}));await waitFor(()=>expect(complete).toHaveBeenCalledWith(task));});
 it('retains task text if save fails',async()=>{render(<JobTaskBoard jobId="job" items={[]} parts={['General']} currentUser={{id:'owner',fullName:'Owner',role:'owner'} as any} crew={[]} canCreate onCreate={vi.fn().mockRejectedValue(new Error('Unable to save'))} onComplete={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'+ Add task'}));fireEvent.change(screen.getByLabelText('What needs doing?'),{target:{value:'Finish rough-in'}});fireEvent.click(screen.getByRole('button',{name:'Save task'}));await screen.findByRole('alert');expect((screen.getByLabelText('What needs doing?') as HTMLInputElement).value).toBe('Finish rough-in');});
});
describe('material request deduplication',()=>{
 function repo(changed=false){let payload:any;const q:any={insert:vi.fn(p=>{payload=p;return q}),select:()=>q,eq:()=>q,single:vi.fn().mockImplementationOnce(()=>Promise.resolve({error:{code:'23505'}})).mockImplementationOnce(()=>Promise.resolve({data:{...payload,...(changed?{quantity:99}:{}),deleted_at:null}}))};return new JobMaterialsRepositoryImpl({orgId:'org',actorUserId:'user'} as any,{from:()=>q} as any);}
 it('returns the original entry for an identical retry',async()=>{const result=await repo().create({requestId:'request',jobId:'job',catalogItemId:'material',kind:'used',quantity:2});expect(result.id).toBe('request');expect(result.quantity).toBe(2);});
 it('rejects a retry with changed data instead of silently replacing it',async()=>{await expect(repo(true).create({requestId:'request',jobId:'job',catalogItemId:'material',kind:'used',quantity:2})).rejects.toThrow('different details');});
});
