import {it,expect,vi} from 'vitest';
import {useState} from 'react';
import {render,screen,fireEvent} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {parseTimeEntryHoursInput} from '@/domain/time-entries/draft';
import {TimeTrackerPanel} from '@/features/workbench/components/TimeTrackerPanel';
it('accepts leading decimals and decimal commas without changing their values',()=>{for(const [raw,expected] of [['.5',.5],['.25',.25],['0.5',.5],['1.5',1.5],[',5',.5],['24',24],['.05',.05]] as const)expect(parseTimeEntryHoursInput(raw)).toBe(expected);});
it('rejects unfinished, out-of-range and overprecise hours rather than clamping them',()=>{for(const value of ['','.','0','-1','25','0.01','1.234','1e2','1..5'])expect(parseTimeEntryHoursInput(value)).toBeNull();});
function Harness({save=vi.fn()}:any){const [draft,setDraft]=useState<any>({jobId:'job',userId:'user',activeTimerId:null,source:'manual',description:'Work',startedAt:'2026-09-14T15:00:00Z',endedAt:'2026-09-14T16:00:00Z'});return <TimeTrackerPanel selectedJobId="job" actualPartOptions={["General"]} onAddPart={name=>name} canCreateTimeEntry availableJobs={[{id:'job',label:'Demo job',canTrack:true}]} availableWorkers={[{id:'user',label:'Worker'}]} draft={draft} activeRunningTimerDraft={null} isSaving={false} runningJobLabel={null} onStart={()=>{}} onStartManual={()=>{}} onUpdateDraft={patch=>setDraft((d:any)=>({...d,...patch}))} onStop={()=>{}} onSave={async()=>save(draft)} onDiscard={()=>{}} onGoToRunningJob={()=>{}}/>;}
it('lets a user type 1.5 through parent updates without removing the decimal',async()=>{const user=userEvent.setup();const save=vi.fn();render(<Harness save={save}/>);const input=screen.getByLabelText('Hours');await user.clear(input);await user.type(input,'1.5');expect((input as HTMLInputElement).value).toBe('1.5');await user.click(screen.getByRole('button',{name:'Save Entry'}));expect(save.mock.calls[0][0].endedAt).toBe('2026-09-14T16:30:00.000Z');});
it('accepts .5 typed one character at a time and saves 30 minutes',async()=>{const user=userEvent.setup();const save=vi.fn();render(<Harness save={save}/>);const input=screen.getByLabelText('Hours');await user.clear(input);await user.type(input,'.5');expect((input as HTMLInputElement).value).toBe('.5');await user.click(screen.getByRole('button',{name:'Save Entry'}));expect(save.mock.calls[0][0].endedAt).toBe('2026-09-14T15:30:00.000Z');});
it('does not silently restore and save an old value after invalid input loses focus',async()=>{const user=userEvent.setup();const save=vi.fn();render(<Harness save={save}/>);const input=screen.getByLabelText('Hours');await user.clear(input);await user.type(input,'.');await user.tab();expect((input as HTMLInputElement).value).toBe('.');expect((screen.getByRole('button',{name:'Save Entry'}) as HTMLButtonElement).disabled).toBe(true);expect(save).not.toHaveBeenCalled();});
