import type { DeviceCatalogItem, RoomType } from "@/domain/takeoff/types";

export const ROOM_TYPE_OPTIONS: Array<{ value: RoomType; label: string }> = [
  { value: "bedroom", label: "Bedroom" },
  { value: "kitchen", label: "Kitchen" },
  { value: "dining_room", label: "Dining room" },
  { value: "living_room", label: "Living room" },
  { value: "bathroom", label: "Bathroom" },
  { value: "ensuite", label: "Ensuite" },
  { value: "hallway", label: "Hallway" },
  { value: "laundry", label: "Laundry" },
  { value: "mechanical_room", label: "Mechanical room" },
  { value: "garage", label: "Garage" },
  { value: "porch_exterior", label: "Porch/exterior" },
  { value: "office_den", label: "Office/den" },
  { value: "closet", label: "Closet" },
  { value: "pantry", label: "Pantry" },
  { value: "unfinished_storage", label: "Unfinished/storage" },
  { value: "other", label: "Other" },
];

export const DEVICE_CATALOG: DeviceCatalogItem[] = [
  pdfDevice("15a-receptacle", "15A receptacle", "Receptacles", "R", "General purpose"),
  pdfDevice("20a-receptacle", "20A receptacle", "Receptacles", "20R", "20A branch"),
  pdfDevice("gfci-receptacle", "GFCI receptacle", "Receptacles", "GFI", "GFCI protected"),
  pdfDevice("exterior-weather-rated-gfci-receptacle", "Exterior weather-rated GFCI receptacle", "Receptacles", "WR", "Weather-rated GFCI"),
  pdfDevice("switch", "1-pole switch", "Controls", "S1", "Lighting control"),
  pdfDevice("3-way-switch", "3-way switch", "Controls", "S3", "Lighting control"),
  pdfDevice("4-way-switch", "4-way switch", "Controls", "S4", "Lighting control"),
  pdfDevice("dimmer", "Dimmer switch", "Controls", "SD", "Lighting control"),
  pdfDevice("motion-switch", "Motion switch", "Controls", "SM", "Lighting control"),
  pdfDevice("ceiling-light", "Ceiling light", "Lighting", "CL", "Lighting"),
  pdfDevice("pot-light", "Pot light/recessed light", "Lighting", "PL", "Lighting"),
  pdfDevice("smoke-alarm", "Smoke alarm", "Life safety", "SA", "Smoke alarm"),
  pdfDevice("co-alarm", "CO alarm", "Life safety", "CO", "CO alarm"),
  pdfDevice("bathroom-fan", "Bath fan", "Lighting", "BF", "Fan"),
  pdfDevice("data-jack", "Data jack", "Low voltage", "DATA", "Data"),
  pdfDevice("tv-coax-outlet", "TV/coax", "Low voltage", "TV", "Coax"),
  pdfDevice("hrv", "HRV", "Dedicated circuits", "HRV", "2c14"),
  pdfDevice("dishwasher", "Dishwasher", "Dedicated circuits", "DW", "2c14"),
  pdfDevice("outdoor-receptacle", "Outdoor receptacle circuit", "Dedicated circuits", "OR", "2c14"),
  pdfDevice("furnace", "Furnace", "Dedicated circuits", "FUR", "2c14"),
  pdfDevice("gas-hwt", "Gas HWT", "Dedicated circuits", "GHW", "2c14"),
  pdfDevice("gas-range", "Gas range", "Dedicated circuits", "GR", "2c14"),
  pdfDevice("fridge", "Fridge", "Dedicated circuits", "FR", "2c14"),
  pdfDevice("heat-trace", "Heat trace", "Dedicated circuits", "HT", "2c14"),
  pdfDevice("radon", "Radon", "Dedicated circuits", "RAD", "2c14"),
  pdfDevice("microwave", "Microwave", "Dedicated circuits", "MW", "2c14"),
  pdfDevice("garage-receptacle", "Garage receptacle circuit", "Dedicated circuits", "GAR", "2c14"),
  pdfDevice("washer", "Washer", "Dedicated circuits", "W", "2c14"),
  pdfDevice("freezer", "Freezer", "Dedicated circuits", "FZ", "2c14"),
  pdfDevice("counter-receptacle", "Counter receptacle circuit", "Dedicated circuits", "CR", "2c12"),
  pdfDevice("baseboard-thermostat", "Baseboard thermostat", "Dedicated circuits", "T", "2c12"),
  pdfDevice("baseboard-heater", "Baseboard heater", "Dedicated circuits", "BB", "2c12"),
  pdfDevice("electric-fireplace", "Electric fireplace", "Dedicated circuits", "EFP", "2c12"),
  pdfDevice("heat-pump", "Heat pump", "Dedicated circuits", "HP", "2c10"),
  pdfDevice("electric-hwt", "Electric HWT", "Dedicated circuits", "EHW", "2c10"),
  pdfDevice("range-outlet", "Range outlet", "Appliance", "RG", "Range"),
  pdfDevice("dryer-outlet", "Dryer outlet", "Appliance", "DR", "Dryer"),
  pdfDevice("heat-pump-disconnect", "Heat pump disconnect", "Appliance", "HPD", "Heat pump disconnect"),
  pdfDevice("ev-charger", "EV charger", "Appliance", "EV", "3c8"),
  pdfDevice("floor-riser", "Floor riser reference", "Service", "RIS", "Cross-floor reference"),
  pdfDevice("panel", "Panel", "Service", "PNL", "Panel"),
  pdfDevice("100a-subpanel", "100A subpanel", "Service", "100SUB", "2c1 NMD"),
  pdfDevice("subpanel", "Subpanel", "Service", "SUB", "Subpanel"),
];

function pdfDevice(id: string, name: string, category: string, symbol: string, circuit: string): DeviceCatalogItem {
  return { id, name, category, symbol, defaultVoltage: "", defaultCircuitType: circuit, roughInBoxType: "", defaultLaborUnit: 0, materialAllowance: 0, notes: "" };
}
