import type { DeviceCatalogItem, RoomType } from "@/domain/takeoff/types";

export const ROOM_TYPE_OPTIONS: Array<{ value: RoomType; label: string }> = [
  { value: "bedroom", label: "Bedroom" },
  { value: "kitchen", label: "Kitchen" },
  { value: "dining_room", label: "Dining room" },
  { value: "living_room", label: "Living room" },
  { value: "bathroom", label: "Bathroom" },
  { value: "ensuite", label: "Ensuite" },
  { value: "hallway", label: "Hallway" },
  { value: "laundry", label: "Laundry" },
  { value: "mechanical_room", label: "Mechanical room" },
  { value: "garage", label: "Garage" },
  { value: "porch_exterior", label: "Porch/exterior" },
  { value: "office_den", label: "Office/den" },
  { value: "closet", label: "Closet" },
  { value: "pantry", label: "Pantry" },
  { value: "unfinished_storage", label: "Unfinished/storage" },
  { value: "other", label: "Other" },
];

export const DEVICE_CATALOG: DeviceCatalogItem[] = [
  createDevice("15A receptacle", "Receptacles", "R", "120V", "General purpose", "Single gang device box", 0.35, 14, "Standard branch receptacle allowance."),
  createDevice("20A receptacle", "Receptacles", "20R", "120V", "20A branch", "Single gang device box", 0.4, 18, "Higher capacity receptacle placeholder."),
  createDevice("GFCI receptacle", "Receptacles", "GFI", "120V", "GFCI protected", "Single gang device box", 0.45, 28, "Use where estimating rules call for GFCI protection."),
  createDevice("AFCI receptacle", "Receptacles", "AFI", "120V", "AFCI protected", "Single gang device box", 0.45, 34, "AFCI placeholder for estimating."),
  createDevice("exterior weather-rated GFCI receptacle", "Receptacles", "WR", "120V", "Weather-rated GFCI", "Weatherproof box", 0.6, 48, "Includes in-use cover allowance."),
  createDevice("countertop kitchen receptacle", "Kitchen", "CTR", "120V", "Small appliance", "Single gang device box", 0.5, 32, "Counter wall estimating placeholder."),
  createDevice("dedicated fridge receptacle", "Kitchen", "FR", "120V", "Dedicated appliance", "Single gang device box", 0.45, 24, "Dedicated fridge location."),
  createDevice("dedicated dishwasher connection", "Kitchen", "DW", "120V", "Dedicated appliance", "Junction box", 0.55, 26, "Connection allowance only."),
  createDevice("garburator connection", "Kitchen", "GD", "120V", "Dedicated appliance", "Junction box", 0.45, 22, "Disposal connection placeholder."),
  createDevice("range outlet", "Kitchen", "RG", "240V", "Range", "Range box", 0.75, 75, "Range circuit placeholder."),
  createDevice("microwave/hood fan outlet", "Kitchen", "MW", "120V", "Dedicated appliance", "Single gang device box", 0.45, 26, "Microwave or hood fan allowance."),
  createDevice("washer outlet", "Laundry", "WA", "120V", "Laundry appliance", "Single gang device box", 0.4, 22, "Washer receptacle placeholder."),
  createDevice("dryer outlet", "Laundry", "DR", "240V", "Dryer", "Dryer receptacle box", 0.7, 62, "Dryer circuit placeholder."),
  createDevice("bathroom fan", "Lighting", "BF", "120V", "Lighting/fan", "Fan-rated rough-in", 0.6, 70, "Fan unit connection allowance."),
  createDevice("vanity light", "Lighting", "VL", "120V", "Lighting", "Octagon box", 0.45, 38, "Vanity light rough-in."),
  createDevice("ceiling light", "Lighting", "CL", "120V", "Lighting", "Octagon box", 0.45, 34, "Basic room light location."),
  createDevice("pot light", "Lighting", "PL", "120V", "Lighting", "Pot light housing", 0.35, 48, "Recessed light placeholder."),
  createDevice("exterior light", "Lighting", "EL", "120V", "Exterior lighting", "Weatherproof light box", 0.55, 45, "Exterior fixture rough-in."),
  createDevice("smoke alarm", "Life safety", "SA", "120V", "Smoke alarm", "Octagon box", 0.35, 38, "Smoke alarm placeholder."),
  createDevice("CO alarm", "Life safety", "CO", "120V", "CO alarm", "Octagon box", 0.35, 38, "Carbon monoxide alarm placeholder."),
  createDevice("switch", "Controls", "S", "120V", "Lighting control", "Single gang switch box", 0.3, 12, "Single pole switch."),
  createDevice("3-way switch", "Controls", "S3", "120V", "Lighting control", "Single gang switch box", 0.35, 16, "Three-way switch."),
  createDevice("4-way switch", "Controls", "S4", "120V", "Lighting control", "Single gang switch box", 0.4, 20, "Four-way switch."),
  createDevice("dimmer", "Controls", "DIM", "120V", "Lighting control", "Single gang switch box", 0.35, 30, "Dimmer placeholder."),
  createDevice("fan switch", "Controls", "FS", "120V", "Fan control", "Single gang switch box", 0.35, 18, "Fan control switch."),
  createDevice("data jack", "Low voltage", "DATA", "Low voltage", "Data", "Low voltage ring", 0.35, 18, "Cat/data jack allowance."),
  createDevice("TV/coax outlet", "Low voltage", "TV", "Low voltage", "Coax", "Low voltage ring", 0.35, 16, "TV/coax outlet allowance."),
  createDevice("thermostat/control wire", "Low voltage", "T", "Low voltage", "Controls", "Low voltage ring", 0.45, 20, "Thermostat or control rough-in."),
  createDevice("panel", "Service", "PNL", "120/240V", "Panel", "Panelboard", 2.5, 450, "Main panel placeholder."),
  createDevice("subpanel", "Service", "SUB", "120/240V", "Subpanel", "Panelboard", 2, 350, "Subpanel placeholder."),
  createDevice("EV charger placeholder", "Special equipment", "EV", "240V", "EV charger", "Equipment rough-in", 1.2, 180, "EV charger rough-in placeholder."),
  createDevice("heat pump/AC disconnect", "Special equipment", "AC", "240V", "HVAC disconnect", "Disconnect", 0.8, 120, "Exterior disconnect allowance."),
  createDevice("hot tub disconnect placeholder", "Special equipment", "HT", "240V", "Hot tub disconnect", "Disconnect", 1, 160, "Hot tub disconnect placeholder."),
];

function createDevice(
  name: string,
  category: string,
  symbol: string,
  defaultVoltage: string,
  defaultCircuitType: string,
  roughInBoxType: string,
  defaultLaborUnit: number,
  materialAllowance: number,
  notes: string,
): DeviceCatalogItem {
  return {
    id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
    name,
    category,
    symbol,
    defaultVoltage,
    defaultCircuitType,
    roughInBoxType,
    defaultLaborUnit,
    materialAllowance,
    notes,
  };
}
