project_id = "bktlwcqllvxkxbeibrhl"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[functions.gmail-finance-import]
verify_jwt = false